Fix BT buffers
telink-semi/hal_telink pull request #54
Opened 2023-09-15 07:58 UTC by TelinkKrystian

It is a partial revert of 604f2c3f7a650e8a0dd8d6e21a20c3432509e45f.

By replacing definition of BT_BUF_TX_SIZE in that commit a HCI_RX_FIFO_SIZE was unintentionally changed. It must stay as it was before in that case since it concerns TX buf size not only ACL, but also CMD buf size.

In case of HCI_RX_ACL_FIFO_SIZE it should have value of BT_BUF_TX_SIZE not ACL_CONN_MAX_RX_OCTETS, because previously it has value of CONFIG_BT_BUF_ACL_TX_SIZE that is completely another value.

2023-09-15 08:50 UTC, andriy-bilynskyy commented
@interfer could you look on this revert. As I remember this commit has been introduced to fix some issue with BT buffers. If we revert it we've got same issue...

2023-09-15 08:53 UTC, andriy-bilynskyy commented
@TelinkKrystian as I understand in scope of your fix you also rebuilt library.
So this new library should be resent in this PR.
See file: zephyr/module.yml
library binaries are stored in https://github.com/telink-semi/zephyr_hal_telink_b91_ble_lib

2023-09-15 09:28 UTC, TelinkKrystian commented
> @interfer could you look on this revert. As I remember this commit has been introduced to fix some issue with BT buffers. If we revert it we've got same issue...

It is only partial issue, not the all changes were reverted ...

2023-09-18 07:26 UTC, andriy-bilynskyy requested changes

2023-09-18 07:26 UTC, andriy-bilynskyy commented on zephyr/module.yml
> +    url: https://github.com/telink-semi/zephyr_hal_telink_b91_ble_lib/raw/8af098db1ab632f84c5be21f369970496fe803cb/liblt_9518_zephyr.a
BLE library merged: SHA a064cf6f8bcb37042dbb7be841933b86e4d095ae

2023-09-19 07:26 UTC, andriy-bilynskyy approved these changes

2023-09-19 07:26 UTC, merged